### PR TITLE
Servermerge

### PR DESCRIPTION
**Pull request by cemac-ccs**
##  Testing in progress - Do not merge yet!

Merge of all three branches. Chooses sensor type (portable/static/server) based on the hostname. An extension of PR #45, and should supercede that PR as this PR also incorporates changes made to the head of the sensor branch since this dev branch was created.

One major feature is that the various sections of uploading code are separated out into their own functions so as to make the main code easier to follow and limit duplicate sections that happen at different times for the different sensor types. This means that the file cannot be automatically merged and so will have to be gone through manually.

The assumptions of the sensor types are:
* Portable sensor should always have a GPS, and may or may not be run continuously
* Static sensor will run continuously, and may or may not have a GPS
* Server will run continuously, may or may not have a GPS and may or may not have an OPC

Timing of the sensors is as follows:

School: 10:00 -14:59
Night: 19:00 - 06:59
Travel: 07:00-09:59 & 15:00 - 18:59

|  | Fast Data Collection | No Data Collection | Stage data | Update Code & Time | Upload Data | 
|---|---|---|---|---|---|
| Portable, Continuous | All  | None | School | School | None |
| Portable, Timed | Travel  | Night | School | School | None |
| Static | All | None | School | School | None |
| Server | All | None | School | Night or Travel | Night or Travel |

### CODE REVIEW

**Comment by wolfiex** [comment]
Overall seems ok. Happy to merge when ready.

**Review by wolfiex — APPROVED** [review]

**Comment by wolfiex** [comment]
@cemac-ccs  conflicts:

Did you push any changes to SensorMod back to the repo (I expect there is a version change if this is coming up)

**Comment by cemac-ccs** [comment]
Fixed conflicts caused by faulty automatic merge, and merged pull req into sensor branch

**Comment by cemac-ccs** [comment]
I think I probably did

Thanks

Chris
___________________________________________________________
Chris Symonds l  Software Development Scientist  l  CEMAC  l
School of Earth and Environment  l  University of Leeds  l  LS2 9JT  l  0113 3438668
________________________________

**Pull request merged**
